// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA77NSvlmZyB_uX4soiT9XDHAvnsJzuFi0',
    appId: '1:121292737965:web:19bbc43f7bff675b776524',
    messagingSenderId: '121292737965',
    projectId: 'wishlist-tracker-f555c',
    authDomain: 'wishlist-tracker-f555c.firebaseapp.com',
    storageBucket: 'wishlist-tracker-f555c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoNqy2eT8Qn7xwjretnGmO0FCTFCiyMyw',
    appId: '1:121292737965:android:664263184195cfb2776524',
    messagingSenderId: '121292737965',
    projectId: 'wishlist-tracker-f555c',
    storageBucket: 'wishlist-tracker-f555c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4Hw1M4ag2wb8fDPTFRZJWMB0wnjrED4k',
    appId: '1:121292737965:ios:4033eb07f5a56562776524',
    messagingSenderId: '121292737965',
    projectId: 'wishlist-tracker-f555c',
    storageBucket: 'wishlist-tracker-f555c.appspot.com',
    iosClientId: '121292737965-bjl3m4qilntcmf29pafoj2ip8g68lv5k.apps.googleusercontent.com',
    iosBundleId: 'com.mark.wishlist',
  );
}
